# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/hotdog/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),hotdog)

$(call add-radio-file-sha1-checked,radio/LOGO.img,1aebad420d5d3f21306b453e769196e78a50a06d)
$(call add-radio-file-sha1-checked,radio/abl.img,3ba00e7bb0d23a5b5b0fb8371f6129441fe422cf)
$(call add-radio-file-sha1-checked,radio/aop.img,2150f091ccb0934cea29f004a557cf38bcce0260)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,54b69d9daf5a3cf69b4bec4e004f58b852be15e1)
$(call add-radio-file-sha1-checked,radio/cmnlib.img,73644dc27d6ae16e4ef4d4d73f65363a93b54836)
$(call add-radio-file-sha1-checked,radio/cmnlib64.img,f466aac6a354f72d3f0cd6b6e0d70a42f28ded46)
$(call add-radio-file-sha1-checked,radio/devcfg.img,ef97a0d4fd2a549f8cce8d17a09065bd1cbaa955)
$(call add-radio-file-sha1-checked,radio/dsp.img,144b07528e20574fcb444aad5f6c906a20335b83)
$(call add-radio-file-sha1-checked,radio/hyp.img,351546bfde11d0e370f01956a3d3806243d19eae)
$(call add-radio-file-sha1-checked,radio/imagefv.img,b63e9714577a07116dfcd4bfc1444af8418b7e1a)
$(call add-radio-file-sha1-checked,radio/keymaster.img,47f673696d8f6f0291a2af65a7a4ad6bf4cf2ccf)
$(call add-radio-file-sha1-checked,radio/modem.img,aa87e248c1a758ea509da533f6fb8725fa3d4e55)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,7f84ec0a6791e41522f73a16566e76372f22c7eb)
$(call add-radio-file-sha1-checked,radio/qupfw.img,32497e84d45e91c37938aef058a4d7f2a21d6288)
$(call add-radio-file-sha1-checked,radio/storsec.img,2aba2af14fb869f69ee6583a361ca7b2a758c239)
$(call add-radio-file-sha1-checked,radio/tz.img,477eaa6a16a715bdb4b1a7406318c7e671c3d27f)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,9ed2e4a890dc57630650a14adae83dd3d1f32c11)
$(call add-radio-file-sha1-checked,radio/xbl.img,d4a7420c59da10e009d435d8a73101703610b81a)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,b158143396d8fd5cfed3b25c8b31227261278e19)

endif
